//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide_Answer
    {
        public int id { get; set; }
        public int test_id { get; set; }
        public int slide_id { get; set; }
        public int slide_choice_id { get; set; }
        public Nullable<System.DateTime> slide_start_time { get; set; }
        public Nullable<System.DateTime> slide_end_time { get; set; }
        public Nullable<System.DateTime> answered { get; set; }
    
        public virtual Slide Slide { get; set; }
        public virtual Slide_Choice Slide_Choice { get; set; }
        public virtual Test Test { get; set; }
    }
}
