//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int id { get; set; }
        public int test_id { get; set; }
        public int slide_id { get; set; }
        public System.DateTime occurred { get; set; }
        public decimal x { get; set; }
        public decimal y { get; set; }
        public Nullable<decimal> dia_x { get; set; }
        public Nullable<decimal> dia_y { get; set; }
        public Nullable<decimal> cr_x { get; set; }
        public Nullable<decimal> cr_y { get; set; }
        public Nullable<decimal> por_x { get; set; }
        public Nullable<decimal> por_y { get; set; }
        public Nullable<int> timing { get; set; }
        public Nullable<int> trigger { get; set; }
    
        public virtual Slide Slide { get; set; }
        public virtual Test Test { get; set; }
    }
}
